export const checkTypeIcon = (type: string): string => {
  const t = type.toLowerCase()
  return t === 'water'
    ? 'water'
    : t === 'bug'
    ? 'bug'
    : t === 'dark'
    ? 'dark'
    : t === 'dragon'
    ? 'dragon'
    : t === 'electric'
    ? 'electric'
    : t === 'fire'
    ? 'fire'
    : t === 'fairy'
    ? 'fairy'
    : t === 'ghost'
    ? 'ghost'
    : t === 'ice'
    ? 'ice'
    : t === 'grass'
    ? 'grass'
    : t === 'psychic'
    ? 'psychic'
    : t === 'rock'
    ? 'rock'
    : t === 'poison'
    ? 'poison'
    : t === 'flying'
    ? 'flying'
    : t === 'normal'
    ? 'normal'
    : t === 'ground'
    ? 'ground'
    : t === 'fighting'
    ? 'fighting'
    : t === 'steel'
    ? 'steel'
    : ''
}
